# Generated by Django 5.2.5 on 2025-11-23 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assignmentunit_paymentplan_programtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programtemplate',
            name='default_unit_count',
            field=models.IntegerField(default=6, help_text='Default number of units (can be overridden in registration)'),
        ),
        migrations.AddField(
            model_name='programtemplate',
            name='forms_weeks',
            field=models.PositiveIntegerField(default=0, help_text='Number of weeks allocated for forms phase'),
        ),
        migrations.AddField(
            model_name='programtemplate',
            name='has_forms_phase',
            field=models.BooleanField(default=False, help_text='ProQual: First 8 weeks for forms'),
        ),
        migrations.AddField(
            model_name='programtemplate',
            name='qualification_type',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('extended', 'Extended Diploma')], help_text='Optional: Specific qualification type for this template', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='programtemplate',
            unique_together={('provider', 'field', 'level', 'qualification_type')},
        ),
        migrations.AddField(
            model_name='registration',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='ops_incentive_paid',
            field=models.BooleanField(default=False, help_text='Ops team incentive paid when coursework completed on time'),
        ),
        migrations.AddField(
            model_name='registration',
            name='program_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.programtemplate'),
        ),
        migrations.AddField(
            model_name='registration',
            name='qualification_type',
            field=models.CharField(blank=True, choices=[('award', 'Award'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('extended', 'Extended Diploma')], help_text='Select qualification type (Award, Certificate, Diploma, Extended)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='sales_incentive_paid',
            field=models.BooleanField(default=False, help_text='Sales team incentive paid when full payment received'),
        ),
        migrations.AddField(
            model_name='registration',
            name='unit_count',
            field=models.PositiveIntegerField(blank=True, help_text='Manually set the number of units for this registration', null=True),
        ),
        migrations.CreateModel(
            name='OperationsIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Incentive amount', max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_on_time', models.BooleanField(default=False, help_text='Whether coursework was completed within deadline')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ops_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_incentives', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ops_incentive', to='core.registration')),
            ],
        ),
        migrations.CreateModel(
            name='SalesIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Incentive amount', max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_incentive', to='core.registration')),
                ('sales_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_incentives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='programtemplate',
            name='unit_count',
        ),
        migrations.CreateModel(
            name='UnitTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_index', models.PositiveIntegerField()),
                ('phase', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=120)),
                ('due_date', models.DateField()),
                ('unit_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.registration')),
            ],
            options={
                'unique_together': {('registration', 'week_index')},
            },
        ),
    ]
