# Generated by Django 5.2.5 on 2025-11-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_programtemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='total_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total fee - used to generate payment installments', max_digits=12, null=True),
        ),
    ]
