# Generated by Django 5.2.5 on 2025-11-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registration_total_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='estimated_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
