# Generated by Django 5.2.5 on 2025-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_make_estimated_completion_date_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='portal_allotment_date',
            field=models.DateField(blank=True, help_text='ProQual: Date when portal was allocated. 32-week timeline starts from this date.', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Sales', 'Sales Team'), ('Ops', 'Operations Team'), ('CEO', 'Chief Executive Officer'), ('ProQualAdmin', 'ProQual Administrator')], max_length=15),
        ),
    ]
