# Generated by Django 5.2.5 on 2025-12-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_registration_portal_allotment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Sales', 'Sales Team'), ('Ops', 'Operations Team'), ('CEO', 'Chief Executive Officer'), ('ProQualAdmin', 'ProQual Administrator'), ('HR', 'Human Resources'), ('Finance', 'Finance')], max_length=20),
        ),
    ]
